### ISSUE TITLE
[Minor] Rename require.txt to requirements.txt 

### ISSUE THREAD

**Issue by wasi0013** [realsirjoe/instagram-scraper#11]
The [recommended](https://pip.pypa.io/en/stable/reference/pip_freeze/#examples) name for the requirements file is `requirements.txt`. Its more like a convention.
Besides, when a file with this name is added to the root project directory, it is automatically detected by various integrated tools and IDE (For example PyCharm) which is very helpful.

**Comment by realsirjoe** [comment]
Thats right, thanks a lot!

Done
