### ISSUE TITLE
 No module named 'igramscraper.instagram'

### ISSUE THREAD

**Issue by supermario1990** [realsirjoe/instagram-scraper#20]
I use 'pip install igramscraper' to install,but got 'ModuleNotFoundError: No module named 'igramscraper.instagram'; 'igramscraper' is not a package' 

then i check whether i installed correctly, igramscraper  package is in 'Python37-32\Lib\site-packages\'

os: win10
python: 3.7.3

**Comment by luengwaiban** [comment]
@supermario1990 do you mean you fail to install or you fail to run?

**Comment by luengwaiban** [comment]
@supermario1990 can you post a screen print about this error here?

**Comment by supermario1990** [comment]
> @supermario1990 do you mean you fail to install or you fail to run?

fail to run,
igramscraper.py contains just one line code, 'from igramscraper.instagram import Instagram'

"D:\Program Files (x86)\Python37-32\python.exe" D:/mypython/scrapy_test/igramscraper.py
Traceback (most recent call last):
  File "D:/mypython/scrapy_test/igramscraper.py", line 1, in <module>
    from igramscraper.instagram import Instagram
  File "D:\mypython\scrapy_test\igramscraper.py", line 1, in <module>
    from igramscraper.instagram import Instagram
ModuleNotFoundError: No module named 'igramscraper.instagram'; 'igramscraper' is not a package

**Comment by supermario1990** [comment]
> @supermario1990 can you post a screen print about this error here?

sorry, because i name the python file as  igramscraper.py, so got the error, I'm so sorry. thank you so much to reply me. i will close the issue
