### ISSUE TITLE
video fields is none

### ISSUE THREAD

**Issue by knsrky** [realsirjoe/instagram-scraper#22]
hello! thanks for awesome scraper!

I get medias by hashtag. But video type media information is blank (such as: video_url)

Can you help?
Thanks again

**Comment by luengwaiban** [comment]
@knsrky after you get medias back by hashtag，you need to call get_media_by_code to get video_url.

**Comment by realsirjoe** [comment]
I am gonna close this issue now. You are welcome to reopen it if you still experience the problem
