### ISSUE TITLE
HTTPSConnectionPool --the proxy seems very easy to reach its limit?

### ISSUE THREAD

**Issue by ivurs** [realsirjoe/instagram-scraper#27]
ProxyError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /miaangler (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x116f3abe0>: Failed to establish a new connection: [Errno 60] Operation timed out',)))

Would you please help me out, it seems that INS still very sensitive to this crawler- am I right?

**Comment by luengwaiban** [comment]
@ivurs it reads Cannot connect to proxy. So what proxy do you use? Did you test your proxy via curl in terminal? your issue do not looks like relevant with our core function...

**Comment by ivurs** [comment]
@luengwaiban  many thanks to your quick response
http://spys.one/en/free-proxy-list/ -- I picked proxy from this website

every time if this exception throw out, I need to manually change another to solve it.

Not sure whether it is because its a company laptop with lots of stupid security limit

**Comment by ivurs** [comment]
@luengwaiban  by the way, would you please also help me to have a look of this error  :
```
~/anaconda3/lib/python3.6/site-packages/igramscraper/instagram.py in login(self, force, two_step_verificator)
   1363                         response.status_code)
   1364 
-> 1365             if not response.json()['authenticated']:
   1366                 raise InstagramAuthException('User credentials are wrong.')
   1367 

KeyError: 'authenticated'

```
the username and pw I input is definitely correct, not sure why cannot login.

**Comment by luengwaiban** [comment]
@ivurs well I will look into it later

**Comment by ivurs** [comment]
@luengwaiban thx in advance

**Comment by realsirjoe** [comment]
Proxies should generally work and are regularly tested! I assume you used bad proxies if thats incorrect and you can still reproduce your error please open a new issue!
