### ISSUE TITLE
Response Code 400 and donwload media problem

### ISSUE THREAD

**Issue by safaklacin** [realsirjoe/instagram-scraper#31]
hi, actually i am a little noob about python, i looked examples, and tried get_medias_by_location_id, at first try it worked well, after second attempt it gives me error. After error instagram gives me *suspicious login attempt" everytime i use this command. here is the result
```
C:\Users\xx\Documents\scraper\examples>python get_medias_by_location_id.py
Traceback (most recent call last):
  File "get_medias_by_location_id.py", line 5, in <module>
    instagram.login()
  File "C:\Users\xx\Documents\scraper\igramscraper\instagram.py", line 1329, in login
    response.status_code)
igramscraper.exception.instagram_auth_exception.InstagramAuthException: Response code is 400. Body: {"message": "checkpoint_
": "/challenge/4046241/7VkRGcz4l2/", "lock": false, "status": "fail"} Something went wrong. Please report issue., Code:400
```
i tried to activate TwoFactorAuth over instagram. I couldn't find where to add that auth codes or what i need to do :/

Edit: after wrote here and couple of tries, delete instagram.login() param it works well, but i have more questions :) i want to download stories and medias (video or image) from location or tag with user infos (profile pic, name, bio) 
is this possible ? if its possible can you help me about this ?

**Comment by realsirjoe** [comment]
Did you fix it?
