### ISSUE TITLE
No one function retrieve account info and last 12 posts captions?

### ISSUE THREAD

**Issue by instasck** [realsirjoe/instagram-scraper#38]
it is all in the same place, why making 2 requests for it ?

**Comment by instasck** [comment]
look at this PR:
https://github.com/instasck/instagram-scraper/commit/74776bc8da7acbb58071c6b15a17bdb59312d720

**Comment by instasck** [comment]
OK it was just a bug:
need to change:
if not self.media_count or isinstance(nodes, list):
to
if not (self.media_count or isinstance(nodes, list)):

:)

**Comment by luengwaiban** [comment]
@instasck would you like to add this code to your PR and we will look into it ~

**Comment by instasck** [comment]
> @instasck would you like to add this code to your PR and we will look into it ~

https://github.com/instasck/instagram-scraper/commit/87f30cbadae755a58a5132edb0c239d2bc13b7ee

look at this commit.
