### ISSUE TITLE
ERROR: No matching distribution found for context.viewer (from context)

### ISSUE THREAD

**Issue by llh1187** [realsirjoe/instagram-scraper#39]
Hello!
Hello everyone! I had a problem. When I installed the package as prompted, the following error occurred.
![image](https://user-images.githubusercontent.com/40154001/62835499-e336b480-bc8b-11e9-8add-6f87a4039d21.png)
my computer: 
  win10 64bit
  Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
  pip 19.2.1 from d:\python37\lib\site-packages\pip (python 3.7)

**Comment by realsirjoe** [comment]
context is not a dependency
