### ISSUE TITLE
Response code 429, rate limited

### ISSUE THREAD

**Issue by SoArZn** [realsirjoe/instagram-scraper#40]
Hi, thanks for your contribution. This is helpful!

I encounter the following error when I increase the number of account to look at:

`igramscraper.exception.instagram_exception.InstagramException: Response code is 429. Body: {"message": "rate limited", "status": "fail"} Something went wrong. Please report issue., Code:429`

May I know about the rate limit and how I should better use this tool? Thanks!

**Comment by realsirjoe** [comment]
when fetching followers go for 50 and 50 page size and make a delay of 5-30 seconds between 500 followers make 5 minute break. Likes and Co have similar limits!

**Comment by skirlen** [comment]
how to set the limit?
