### ISSUE TITLE
IG not retrieving ProfilePage info when on Proxy

### ISSUE THREAD

**Issue by instasck** [realsirjoe/instagram-scraper#42]
All worked well and smooth untl few hours a go.

I tried the user with proxy and got:
    if user_array['entry_data']['ProfilePage'][0]['graphql']['user'] is None:
KeyError: 'ProfilePage'

So I tried without and all seems to be working.
Any suggestions ? maybe the proxy is fault ?

**Comment by realsirjoe** [comment]
Just tried it with a few open proxies (try out a few yourself) for me it worked so its likely your proxies fault

**Comment by instasck** [comment]
Hi

**Comment by instasck** [comment]
Did you try while logged in to an account ?
it will work for about 50 - 100 scrapping, after it will not contain the ProfilePage info but will get res from IG.

My solution was to use 4g proxies without login in - they can't block this.
BTW, google server ip also was blocked after 100 times without logging in.
