### ISSUE TITLE
KeyError: 'ProfilePage

### ISSUE THREAD

**Issue by ZIVVAL** [realsirjoe/instagram-scraper#44]
All worked well and smooth untl few hours a go.

I tried the user with proxy and got:
if user_array['entry_data']['ProfilePage'][0]['graphql']['user'] is None:
KeyError: 'ProfilePage'

So I tried without and all seems to be working for few times and again  keyError: ProfilePage
Any suggestions

**Comment by suxSx** [comment]
Looks like your instagram user you used to login with have request to much from instagram so your user are no longer able to retrive the information. Wait a couple of minutes or change login user and it should work just fine.

**Comment by instasck** [comment]
@suxSx I now don't use a login user just scrape without user and a 4g proxy.
It seems to not work for 50% of times with return code:
{'config': {'csrf_token': '5aS6alZEvNVGGRlKCxYwxaHM4JJASvMZ', 'viewer': None, 'viewerId': None}, 'country_code': 'IL', 'language_code': 'en', 'locale': 'en_US', 'entry_data': {'ProfilePage': [{'logging_page_id': 'prof

What can I do ?

**Comment by jrdnbrj** [comment]
I am having the same problem and I do not use user login.
Is there anything I can do?
