### ISSUE TITLE
500 error when trying to get paginated medias

### ISSUE THREAD

**Issue by wisosonic** [realsirjoe/instagram-scraper#45]
In get_paginate_medias, change line 628 :

`variables = json.dumps({
            'id': str(account.identifier),
            'first': str(endpoints.request_media_count),
            'after': str(max_id)
        }, separators=(',', ':'))`

to :

`variables = {
            'id': str(account.identifier),
            'first': str(endpoints.request_media_count),
            'after': str(max_id)
        }`

**Comment by realsirjoe** [comment]
this was a bug and has been fixed recently, thanks for pointing it out!
