### ISSUE TITLE
SyntaxError: invalid syntax - with version 0.3.2

### ISSUE THREAD

**Issue by mspapant** [realsirjoe/instagram-scraper#46]
I am using the version 0.3.2. 

When i am trying to execute the simple script from the readme i get:

> Traceback (most recent call last):
  File "igramscrepertest.py", line 1, in <module>
    from igramscraper.instagram import Instagram
  File "/usr/local/lib/python3.5/dist-packages/igramscraper/instagram.py", line 153
    cookies += f"{key}={session[key]}; "
                                       ^
SyntaxError: invalid syntax

The code i am running is: 

> 
from igramscraper.instagram import Instagram

instagram = Instagram()
instagram.with_credentials('******', '*******')
instagram.login()

account = instagram.get_account_by_id(3)

print('Account info:')
print('Id: ', account.identifier)
print('Username: ', account.username)
print('Full name: ', account.full_name)
print('Biography: ', account.biography)
print('Profile pic url: ', account.get_profile_pic_url_hd())
print('External Url: ', account.external_url)
print('Number of published posts: ', account.media_count)
print('Number of followers: ', account.followed_by_count)
print('Number of follows: ', account.follows_count)
print('Is private: ', account.is_private)
print('Is verified: ', account.is_verified)

**Comment by mertsalik** [comment]
Its because f strings introduced with 3.6 version.
https://www.python.org/dev/peps/pep-0498/

**Comment by realsirjoe** [comment]
solved
