### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by Bha91** [realsirjoe/instagram-scraper#53]
`        ERROR: Command errored out with exit status 1:
     .........
      File "c:\users\user\appdata\local\temp\pip-install-ro86ut\igramscraper\setup.py", line 8, in <module>
        long_description=Path("README.md").read_text(),
    AttributeError: 'WindowsPath' object has no attribute 'read_text'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by realsirjoe** [comment]
this is unrelated to the lib please refer to the python docs
