### ISSUE TITLE
get account by id eror

### ISSUE THREAD

**Issue by amitabduls15** [realsirjoe/instagram-scraper#54]
when i try get info account by this function, eror 404 something went wrong

**Comment by mspapant** [comment]
me2

**Comment by mymggithub** [comment]
if you are talking about 

`account = instagram.get_account_by_id(3)`

I get a code 400

the error looks something like this

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/igramscraper/instagram.py", line 110, in get_account_by_id
    username = self.get_username_by_id(id)
  File "/usr/local/lib/python3.7/dist-packages/igramscraper/instagram.py", line 129, in get_username_by_id
    response.status_code)
igramscraper.exception.instagram_exception.InstagramException: Response code is 400. Body: {"message": "useragent mismatch", "status": "fail"} Something went wrong. Please report issue., Code:400
```

**Comment by MaxPavlushin** [comment]
Recently it worked, but now it doesn’t work for me either.

**Comment by lkl2050** [comment]
> if you are talking about
> 
> `account = instagram.get_account_by_id(3)`
> 
> I get a code 400
> 
> the error looks something like this
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.7/dist-packages/igramscraper/instagram.py", line 110, in get_account_by_id
>     username = self.get_username_by_id(id)
>   File "/usr/local/lib/python3.7/dist-packages/igramscraper/instagram.py", line 129, in get_username_by_id
>     response.status_code)
> igramscraper.exception.instagram_exception.InstagramException: Response code is 400. Body: {"message": "useragent mismatch", "status": "fail"} Something went wrong. Please report issue., Code:400
> ```

same issue here

**Comment by LouisGerard** [comment]
Here is the right user agent : `Instagram 126.0.0.25.121 Android (23/6.0.1; 320dpi; 720x1280; samsung; SM-A310F; a3xelte; samsungexynos7580; en_GB; 110937453)`. You may need to update the version.

**Comment by hdn7** [comment]
> Here is the right user agent : `Instagram 126.0.0.25.121 Android (23/6.0.1; 320dpi; 720x1280; samsung; SM-A310F; a3xelte; samsungexynos7580; en_GB; 110937453)`. You may need to update the version.

I have installed the last version but it stills occurs. I had to manually change the user agent in the site-packages/igramscraper/instagram.py

**Comment by lnalex** [comment]
Just submitted a pull request to fix this issue
