### ISSUE TITLE
deleting cookies everytime

### ISSUE THREAD

**Issue by sionking** [realsirjoe/instagram-scraper#62]
I don't get why we remove the cookies every time we start, so login will happen again?
```

        if isinstance(session_folder, str):

            Instagram.instance_cache = CookieSessionManager(
                session_folder, slugify(username) + '.txt')

        else:
            Instagram.instance_cache = session_folder

        Instagram.instance_cache.empty_saved_cookies()
```

 Instagram.instance_cache.empty_saved_cookies() will call every time!

**Comment by shahreahang** [comment]
I have same problem !
did you solve this problem ?
I remove the line but its not working....
