### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by myboxtcp** [realsirjoe/instagram-scraper#66]
i'm receiving the following error when i attempt to run the script- how do i rectify this?

(base) C:\Instagramscraper\igramscraper>python instagram.py
Traceback (most recent call last):
  File "instagram.py", line 9, in <module>
    from .session_manager import CookieSessionManager
ModuleNotFoundError: No module named '__main__.session_manager'; '__main__' is not a package

**Comment by realsirjoe** [comment]
Make sure you are not using the lib incorrect. Test the samples on the readme first to assure everything works!
