### ISSUE TITLE
comments replies

### ISSUE THREAD

**Issue by bernardovianna** [realsirjoe/instagram-scraper#70]
Is it possible to scrape comments' replies? I can get the top-level comments of a post, but I could not find how to get the replies to each comment.

**Comment by bddexter** [comment]
Sure:

`https://www.instagram.com/graphql/query/?query_hash=1ee91c32fc020d44158a3192eda98247&variables={"comment_id":"17996676514302377","first":100}`

**Comment by realsirjoe** [comment]
solved

**Comment by rbtrrnss** [comment]
Sorry to reply to an old issue again. But I don't get the solution by @bddexter .
Which method do I need to use to scrape the replies once I have the URL/comment ID?
I only found methods supporting pagination for media, but not comments.

**Comment by bddexter** [comment]
Youcan use the `url` above (still works): `https://www.instagram.com/graphql/query/?query_hash=1ee91c32fc020d44158a3192eda98247&variables={"comment_id":"17996676514302377","first":100}`

**Comment by rbtrrnss** [comment]
Thank you for the fast answer!
You're right, the URL still works, so from there I basically `urllib.request` and `json` my way through the data?
If there is a more convenient method, I'd be glad, but I'm fine if it works like this right now.

**Comment by bddexter** [comment]
You just loop trhough the `json` yes. There's also info on the total amount of comments so you can determine how many loops you have to do (this is how I did in in `php`).

**Comment by rbtrrnss** [comment]
Maybe I need to check the php based version for some other functions, too.
Again, thanks for your answer, this is definitely helpful!

**Comment by olyamarch** [comment]
> Thank you for the fast answer! You're right, the URL still works, so from there I basically `urllib.request` and `json` my way through the data? If there is a more convenient method, I'd be glad, but I'm fine if it works like this right now.

Could you please  share how exactly you managed to get comments reply? Would much appreciate

**Comment by olyamarch** [comment]
> Youcan use the `url` above (still works): `https://www.instagram.com/graphql/query/?query_hash=1ee91c32fc020d44158a3192eda98247&variables={"comment_id":"17996676514302377","first":100}`

How can I get a link to a parent comments page? All the comments of a certain media? Thank you
