### ISSUE TITLE
how to export username to a txt or csv file 

### ISSUE THREAD

**Issue by Abdulsamipy** [realsirjoe/instagram-scraper#74]
Hi guys , so i'm using "**get_account_followers.py**" ..i was wondering if it is possible to export certain details like username to a .csv or a .txt file

**Comment by alanwuha** [comment]
Hey @Abdulsamipy in case you still need a solution to this, you can do with with this:

with open('followers.csv', 'w', encoding='utf8') as f:
  for follower in followers['accounts']:
    f.write(follower.username + '\n')
f.close()

**Comment by realsirjoe** [comment]
solved

**Comment by abindadna** [comment]
hi, i have added script from @alanwuha and **csv import** in the header but it still error. This is the error message

```
File "get_account_followers.py", line 20
    with open('followers.txt', 'w', encoding='utf8') as f:
                                                         ^
IndentationError: unindent does not match any outer indentation level
```

Can you help me?

**Comment by alanwuha** [comment]
Hey @abindadna can you share your code for the `get_account_followers.py` script here? Do exclude your ig credentials from the code.

Also, which python version are you using?

It seems like an [indentation error](https://stackoverflow.com/questions/492387/indentationerror-unindent-does-not-match-any-outer-indentation-level). You might be mixing up spaces with tabs or vice versa.
