### ISSUE TITLE
Could not extract gis from page, Code:500

### ISSUE THREAD

**Issue by DongjinLiu** [realsirjoe/instagram-scraper#79]
When I want get the comments of media, sometime, for some medias, it will raise a exception: 'Could not extract gis from page, Code:500'. How can I solve this problem?

**Comment by realsirjoe** [comment]
this was a bug and should be solved now, if not feel free to open a new issue

**Comment by anumerico** [comment]
IM getting that too now.. Could you clarify what kinf of bug it was and how you fixed it?
